/* 
* ALP version 1.0

* Copyright © 2024 kt corp. All rights reserved.

* 

* This is a proprietary software of kt corp, and you may not use this file except in

* compliance with license agreement with kt corp. Any redistribution or use of this

* software, with or without modification shall be strictly prohibited without prior written

* approval of kt corp, and the copyright notice above does not evidence any actual or

* intended publication of such software.

*/

interface ChartConfig {
	name: string | string[];
	title: string;
	type: string | string[];
	xlabel: string;
	color: string[];
	summary?: string;
	isSingleTable?: boolean;
	isExceptionalChart?: boolean;
	chartUnit: string;
}
export const alpChartConfig: ChartConfig[] = [
	//생활인구현황
	{
		name: "timeSeriesData",
		title: "시계열 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["lastyearDataAvg", "lastyearDataUnique"],
		title: "전년 동기 내국인 생활인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: ["preMonthDataAvg", "preMonthDataUnique"],
		title: "전월 내국인 생활인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: ["monthDataAvg", "monthDataUnique"],
		title: "일별 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: ["genderageDataAvg", "genderageDataUnique"],
		title: "성연령별 내국인 생활인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: ["weekData"],
		title: "요일별 내국인 생활인구",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: ["weekedData"],
		title: "평일,휴일별 내국인 생활인구",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "timeGenderPopData",
		title: "시간대별 성별 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "timeAgePopData",
		title: "시간대별 연령대별 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
		],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "timeDayPopData",
		title: "시간대별 요일별 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "timeWeekPopData",
		title: "시간대별 평일/휴일별 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "districtData",
		title: "하위 행정구역별, 시간대별 생활인구",
		type: ["heatmap", "table"],
		xlabel: "구분",
		color: ["#E5F0FE", "#B9D3F5", "#68A3F1", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "inflowData",
		title: "평일별 유입지역",
		type: ["horizontalBar", "sankey", "table"],
		xlabel: "구분",
		color: [
			"#3473E7",
			"#4580E9",
			"#588EEB",
			"#80AAEE",
			"#6B9CED",
			"#94B9F1",
			"#AAC8F2",
			"#C1D7F5",
			"#D9E6F6",
			"#F1F5F9",
		],
		chartUnit: "명",
	},
	{
		name: "outflowData",
		title: "평일별 유출지역",
		type: ["horizontalBar", "sankey", "table"],
		xlabel: "구분",
		color: [
			"#3473E7",
			"#4580E9",
			"#588EEB",
			"#80AAEE",
			"#6B9CED",
			"#94B9F1",
			"#AAC8F2",
			"#C1D7F5",
			"#D9E6F6",
			"#F1F5F9",
		],
		chartUnit: "명",
	},
	{
		name: "weekendInflowData",
		title: "휴일별 유입지역",
		type: ["horizontalBar", "sankey", "table"],
		xlabel: "구분",
		color: [
			"#69BEB7",
			"#76C3BE",
			"#82CAC4",
			"#90D0CB",
			"#9ED6D2",
			"#ABDDD8",
			"#BAE3E0",
			"#C9E9E7",
			"#D7F0ED",
			"#E6F6F5",
		],
		chartUnit: "명",
	},

	{
		name: "weekendOutflowData",
		title: "휴일별 유출지역",
		type: ["horizontalBar", "sankey", "table"],
		xlabel: "구분",
		color: [
			"#47759F",
			"#5682A8",
			"#678FB1",
			"#789DBC",
			"#8AAAC5",
			"#9DB8CF",
			"#B0C6D8",
			"#C4D5E3",
			"#D8E3ED",
			"#ECF2F7",
		],
		chartUnit: "명",
	},
	{
		name: "foreignerLastyearData",
		title: "전년 동기 외국인 생활인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "foreignerPreMonthData",
		title: "전월 외국인 생활인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "foreignerMonthData",
		title: "일별 외국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		chartUnit: "명",
	},
	{
		name: "foreignerWeekData",
		title: "요일별 외국인 생활인구",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "foreignerTimeData",
		title: "시간대별 외국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		chartUnit: "명",
	},
	{
		name: "foreignerTimeCountryData",
		title: "시간대별 국가별 외국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
		],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "foreignerData",
		title: "국가별 외국인 생활인구 비중",
		type: ["pie", "bar", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
		],
		isSingleTable: true,
		chartUnit: "명",
	},

	//생활패턴분석
	{
		name: ["pCurrentDataAvg", "pCurrentDataUnique"],
		title: "월별 거주/직장/방문 인구 현황",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		chartUnit: "명",
	},
	{
		name: ["pMonthDataAvg", "pMonthDataUnique"],
		title: "월별 거주/직장/방문 인구 비교",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pDayDataAvg", "pDayDataUnique"],
		title: "일별 거주/직장/방문 인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pGenderDataAvg", "pGenderDataUnique"],
		title: "성별 거주/직장/방문 인구",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: ["pAgeDataAvg", "pAgeDataUnique"],
		title: "연령별 거주/직장/방문 인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		isSingleTable: true,
		chartUnit: "명",
	},

	//추가됨
	{
		name: ["pGenderAgeResidenceDataAvg", "pGenderAgeResidenceDataUnique"],
		title: "성연령별 거주 인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pGenderAgeWorkerDataAvg", "pGenderAgeWorkerDataUnique"],
		title: "성연령별 직장 인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pGenderAgeVisitorDataAvg", "pGenderAgeVisitorDataUnique"],
		title: "성연령별 방문 인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pWeekData"],
		title: "요일별 거주/직장/방문 인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pWeekedData"],
		title: "평일, 휴일별 거주/직장/방문 인구",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		chartUnit: "%",
	},
	{
		name: "pTimeData",
		title: "시간대별 거주/직장/방문 인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		isSingleTable: true,
		chartUnit: "명",
	},

	//주민생활비교분석
	{
		name: "currentData",
		title: "거주인구와 주민등록인구 현황",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "cMonthData",
		title: "월별 주민등록인구 대비 거주인구 비교",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "cDayData",
		title: "일별 주민등록인구 대비 거주인구 비교",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "cGenderData",
		title: "성별 거주인구와 주민등록인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: "cAgeData",
		title: "연령별 거주인구와 주민등록인구 비교",
		type: ["bar", "line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	//추가됨
	{
		name: "cGenderAgeResidenceData",
		title: "성연령별 거주인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "cGenderAgeRegisteredData",
		title: "성연령별 주민등록인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "cDistrictData",
		title: "거주인구와 주민등록인구 수 비교",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "cDistrictStackData",
		title: "거주인구와 주민등록인구 누적 비율 비교",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "%",
	},
	{
		name: "modalCurrentData",
		title: "주민등록인구 현황",
		type: ["bar", "line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		chartUnit: "명",
	},
	{
		name: "modalYearData",
		title: "연도별 주민등록인구 수",
		type: ["bar", "line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		chartUnit: "명",
	},
	{
		name: "modalMoveData",
		title: "순이동 인구 수",
		type: ["horizontalBar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "yearMoveData",
		title: "연도별 사유별 순이동 인구 수",
		type: ["heatmap", "table"],
		xlabel: "구분",
		color: ["#E5F0FE", "#B9D3F5", "#68A3F1", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "extinctionData",
		title: "지방소멸위험지수",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "점",
		isSingleTable: true,
	},
	{
		name: "modalGenderData",
		title: "주민등록인구 성별 현황",
		type: ["pie", "bar", "table"],
		xlabel: "구분",
		color: ["#5372F6", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: "modalAgeData",
		title: "주민등록인구 연령별 현황",
		type: ["pie", "bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "명",
	},

	// 랭킹분석
	{
		name: ["preYearDataAvg", "preYearDataUnique"],
		title: "전년 동기 주요 지표별 추이",
		type: ["radar", "table"],
		xlabel: "구분",
		color: ["rgba(47, 128, 237, 1)", "rgba(213, 108, 246, 1)"],
		isSingleTable: true,
		chartUnit: "%",
	},
	{
		name: ["flowDataAvg"],
		title: "생활인구 유입-유출 분포",
		type: ["sankey", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#7C69EF", "#5789AF", "#16BFD6", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: ["alpRaceDataAvg"],
		title: "시군구 지역 랭킹",
		type: ["tableGroup", "race", "bump"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: ["alpRaceTownDataAvg"],
		title: "읍면동 지역 랭킹",
		type: ["tableGroup", "race", "bump"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},

	//비교화면 생활인구현황
	{
		name: "timeSeriesDataGroup",
		title: "시계열 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["lastyearDataGroupAvg", "lastyearDataGroupUnique"],
		title: "전년 동기 내국인 생활인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: ["preMonthDataGroupAvg", "preMonthDataGroupUnique"],
		title: "전월 내국인 생활인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: ["monthDataGroupAvg", "monthDataGroupUnique"],
		title: "일별 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#5789AF", "#79C8C4", "#7C69EF"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: ["genderageDataGroupAvg", "genderageDataGroupUnique"],
		title: "성연령별 내국인 생활인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: ["weekDataGroup"],
		title: "요일별 내국인 생활인구",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: ["weekedDataGroup"],
		title: "평일,휴일별 내국인 생활인구",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "timeGenderPopDataGroup",
		title: "시간대별 성별 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "timeAgePopDataGroup",
		title: "시간대별 연령대별 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
		],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "timeDayPopDataGroup",
		title: "시간대별 요일별 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "timeWeekPopDataGroup",
		title: "시간대별 평일/휴일별 내국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "districtDataGroup",
		title: "하위 행정구역별, 시간대별 생활인구",
		type: ["heatmap", "table"],
		xlabel: "구분",
		color: ["#E5F0FE", "#B9D3F5", "#68A3F1", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "inflowDataGroup",
		title: "평일별 유입지역",
		type: ["horizontalBar", "sankey", "table"],
		xlabel: "구분",
		color: [
			"#3473E7",
			"#4580E9",
			"#588EEB",
			"#80AAEE",
			"#6B9CED",
			"#94B9F1",
			"#AAC8F2",
			"#C1D7F5",
			"#D9E6F6",
			"#F1F5F9",
		],
		chartUnit: "명",
	},
	{
		name: "outflowDataGroup",
		title: "평일별 유출지역",
		type: ["horizontalBar", "sankey", "table"],
		xlabel: "구분",
		color: [
			"#3473E7",
			"#4580E9",
			"#588EEB",
			"#80AAEE",
			"#6B9CED",
			"#94B9F1",
			"#AAC8F2",
			"#C1D7F5",
			"#D9E6F6",
			"#F1F5F9",
		],
		chartUnit: "명",
	},
	{
		name: "weekendInflowDataGroup",
		title: "휴일별 유입지역",
		type: ["horizontalBar", "sankey", "table"],
		xlabel: "구분",
		color: [
			"#69BEB7",
			"#76C3BE",
			"#82CAC4",
			"#90D0CB",
			"#9ED6D2",
			"#ABDDD8",
			"#BAE3E0",
			"#C9E9E7",
			"#D7F0ED",
			"#E6F6F5",
		],
		chartUnit: "명",
	},
	{
		name: "weekendOutflowDataGroup",
		title: "휴일별 유출지역",
		type: ["horizontalBar", "sankey", "table"],
		xlabel: "구분",
		color: [
			"#47759F",
			"#5682A8",
			"#678FB1",
			"#789DBC",
			"#8AAAC5",
			"#9DB8CF",
			"#B0C6D8",
			"#C4D5E3",
			"#D8E3ED",
			"#ECF2F7",
		],
		chartUnit: "명",
	},
	{
		name: "foreignerLastyearDataGroup",
		title: "전년 동기 외국인 생활인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "foreignerPreMonthDataGroup",
		title: "전월 외국인 생활인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "foreignerMonthDataGroup",
		title: "일별 외국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "명",
	},
	{
		name: "foreignerWeekDataGroup",
		title: "요일별 외국인 생활인구",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "foreignerTimeDataGroup",
		title: "시간대별 외국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "명",
	},
	{
		name: "foreignerTimeCountryDataGroup",
		title: "시간대별 국가별 외국인 생활인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
		],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "foreignerDataGroup",
		title: "국가별 외국인 생활인구 비중",
		type: ["pie", "bar", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
		],
		isSingleTable: true,
		chartUnit: "명",
	},

	//비교화면 생활패턴분석
	{
		name: ["pCurrentDataGroupAvg", "pCurrentDataGroupUnique"],
		title: "월별 거주/직장/방문 인구 현황",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#5789AF", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pMonthDataGroupAvg", "pMonthDataGroupUnique"],
		title: "월별 거주/직장/방문 인구 비교",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#5789AF", "#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pDayDataGroupAvg", "pDayDataGroupUnique"],
		title: "일별 거주/직장/방문 인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#5789AF", "#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pGenderDataGroupAvg", "pGenderDataGroupUnique"],
		title: "성별 거주/직장/방문 인구",
		type: ["custom", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: ["pAgeDataGroupAvg", "pAgeDataGroupUnique"],
		title: "연령대별 거주/직장/방문 인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#5789AF", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: ["pGenderAgeResidenceDataGroupAvg", "pGenderAgeResidenceDataGroupUnique"],
		title: "성연령별 거주 인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pGenderAgeWorkerDataGroupAvg", "pGenderAgeWorkerDataGroupUnique"],
		title: "성연령별 직장 인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pGenderAgeVisitorDataGroupAvg", "pGenderAgeVisitorDataGroupUnique"],
		title: "성연령별 방문 인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pWeekDataGroup"],
		title: "요일별 거주/직장/방문 인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#5789AF", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: ["pWeekedDataGroup"],
		title: "평일, 휴일별 거주/직장/방문 인구",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#5789AF", "#79C8C4"],
		chartUnit: "%",
	},
	{
		name: "pTimeDataGroup",
		title: "시간대별 거주/직장/방문 인구",
		type: ["line", "tableGroup"],
		xlabel: "구분",
		color: ["#5789AF", "#418AEC", "#79C8C4"],
		chartUnit: "명",
	},

	//주민생활비교분석
	{
		name: "currentDataGroup",
		title: "거주인구와 주민등록인구 현황",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "cMonthDataGroup",
		title: "월별 주민등록인구 대비 거주인구 비교",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "cDayDataGroup",
		title: "일별 주민등록인구 대비 거주인구 비교",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#5789AF", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "cGenderDataGroup",
		title: "성별 거주인구와 주민등록인구 비교",
		type: ["custom", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: "cAgeDataGroup",
		title: "연령별 거주인구와 주민등록인구 비교",
		type: ["bar", "line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},

	//추가됨
	{
		name: "cGenderAgeResidenceDataGroup",
		title: "성연령별 거주인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "cGenderAgeRegisteredDataGroup",
		title: "성연령별 주민등록인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "cDistrictDataGroup",
		title: "거주인구와 주민등록인구 수 비교",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "cDistrictStackDataGroup",
		title: "거주인구와 주민등록인구 누적 비율 비교",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "%",
	},
	// {
	// 	name: "modalCurrentDataGroup",
	// 	title: "주민등록인구 현황",
	// 	type: ["bar", "line", "table"],
	// 	xlabel: "구분",
	// 	color: ["#418AEC"],
	// 	chartUnit: "명",
	// },
	// {
	// 	name: "modalYearDataGroup",
	// 	title: "연도별 주민등록인구 수",
	// 	type: ["bar", "line", "table"],
	// 	xlabel: "구분",
	// 	color: ["#418AEC"],
	// 	chartUnit: "명",
	// },
	// {
	// 	name: "modalMoveDataGroup",
	// 	title: "순이동 인구 수",
	// 	type: ["horizontalBar", "table"],
	// 	xlabel: "구분",
	// 	color: ["#418AEC", "#79C8C4"],
	// 	chartUnit: "명",
	// },
	// {
	// 	name: "yearMoveDataGroup",
	// 	title: "연도별 사유별 순이동 인구 수",
	// 	type: ["heatmap", "table"],
	// 	xlabel: "구분",
	// 	color: ["#E5F0FE", "#B9D3F5", "#68A3F1", "#418AEC"],
	// 	chartUnit: "명",
	// },
	// {
	// 	name: "extinctionDataGroup",
	// 	title: "지방소멸위험지수",
	// 	type: ["bar", "table"],
	// 	xlabel: "구분",
	// 	color: ["#418AEC", "#79C8C4"],
	// 	chartUnit: "점",
	// },
	// {
	// 	name: "modalGenderDataGroup",
	// 	title: "주민등록인구 성별 현황",
	// 	type: ["pie", "bar", "table"],
	// 	xlabel: "구분",
	// 	color: ["#5372F6", "#FF6362"],
	// 	chartUnit: "명",
	// },
	// {
	// 	name: "modalAgeDataGroup",
	// 	title: "주민등록인구 연령별 현황",
	// 	type: ["pie", "table"],
	// 	xlabel: "구분",
	// 	color: ["#418AEC", "#5789AF", "#79C8C4", "#7C69EF"],
	// 	chartUnit: "명",
	// },

	// 랭킹분석
	{
		name: ["preYearDataGroupAvg", "preYearDataGroupUnique"],
		title: "전년 동기 주요 지표별 추이",
		type: ["radar", "table"],
		xlabel: "구분",
		color: ["#3C8FED", "#D56CF6"],
		isSingleTable: true,
		chartUnit: "%",
	},
	{
		name: ["flowDataGroupAvg"],
		title: "생활인구 유입-유출 분포",
		type: ["sankey", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#7C69EF", "#5789AF", "#16BFD6", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: ["alpRaceDataGroupAvg"],
		title: "시군구 지역 랭킹",
		type: ["tableGroup", "race", "bump"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},

	{
		name: ["alpRaceTownDataGroupAvg"],
		title: "읍면동 지역랭킹",
		type: ["tableGroup", "race", "bump"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: ["llpShortStayRatioData"],
		title: "숙박일수별 비율",
		type: ["pie", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "일",
	},
];
