/* 
* ALP version 1.0

* Copyright © 2024 kt corp. All rights reserved.

* 

* This is a proprietary software of kt corp, and you may not use this file except in

* compliance with license agreement with kt corp. Any redistribution or use of this

* software, with or without modification shall be strictly prohibited without prior written

* approval of kt corp, and the copyright notice above does not evidence any actual or

* intended publication of such software.

*/

interface ChartConfig {
	name: string | string[];
	title: string;
	type: string | string[];
	xlabel: string;
	color: string[];
	summary?: string;
	isSingleTable?: boolean;
	isExceptionalChart?: boolean;
	chartUnit: string;
}

export const llpChartConfig: ChartConfig[] = [
	//체류인구현황
	{
		name: "llpMapData",
		title: "전국 인구감소지역 체류인구 배수",
		type: ["map"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "배",
	},
	{
		name: "llpPreYMonthData",
		title: "전년 동기 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "llpPremonthData",
		title: "전월 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "llpHourDayData",
		title: "일별 체류인구 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "llpHourWeekData",
		title: "평일/휴일별 체류인구",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "llpHourWeekPerData",
		title: "평일/휴일별 체류인구 비중",
		type: ["fullStack", "pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "%",
	},

	{
		name: "llpGenderAgeData",
		title: "성연령별 체류인구 분포",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#5372F6", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
		isExceptionalChart: true,
	},
	{
		name: "llpMonthGenderData",
		title: "월별 연령대별 체류인구 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
			"#FF7658",
			"#FF6BA1",
			"#94AE55",
			"#349D74",
			"#3A66B8",
			"#B94CAA",
		],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "llpCurrentData",
		title: "주민등록인구 대비 체류인구 현황",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "llpMotchComparativeData",
		title: "월별 비교",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "llpHourMonthSexData",
		title: "성별 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "%",
	},
	{
		name: "llpHourMonthAgeData",
		title: "연령별 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "%",
	},

	//체류인구특성
	{
		name: "llpStayDaysRatioData",
		title: "체류일수별 비중",
		type: ["pie", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		chartUnit: "%",
	},
	{
		name: "llpAvgDaysOfStayData",
		title: "평균 체류일수",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "일",
	},
	// {
	// 	name: "llpStayDaysPeopleData",
	// 	title: "체류일수별 체류인구",
	// 	type: ["bar", "table"],
	// 	xlabel: "구분",
	// 	color: ["#418AEC", "#79C8C4", "#7C69EF"],
	// },
	{
		name: "llpGenderStayData",
		title: "체류일수별 성별 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: "llpAgeGroupStayData",
		title: "체류일수별 연령별 분포",
		type: ["stack", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
			"#FF7658",
			"#FF6BA1",
			"#94AE55",
			"#349D74",
			"#3A66B8",
			"#B94CAA",
		],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "llpStayOverRatioData",
		title: "숙박일수별 비중",
		type: ["pie", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "%",
	},
	{
		name: "llpAverageStayOverDaysData",
		title: "평균 숙박일수",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "일",
	},
	{
		name: "llpShortStayRatioData",
		title: "숙박일수별 비율",
		type: ["pie", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "일"
	},
	{
		name: "llpGenderStayOverData",
		title: "숙박일수별 성별 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: "llpAgeGroupStayOverData",
		title: "숙박일수별 연령별 분포",
		type: ["stack", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
			"#FF7658",
			"#FF6BA1",
			"#94AE55",
			"#349D74",
			"#3A66B8",
			"#B94CAA",
		],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "llpExternalResidentStayRatioData",
		title: "타시도 거주자 체류 비중",
		type: ["fullStack", "pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "%",
	},
	{
		name: "llpTop10InboundAreasData",
		title: "외부 유입지역 상위 TOP 10",
		type: ["horizontalBar", "bar", "table"],
		xlabel: "구분",
		color: [
			"#3473E7",
			"#4580E9",
			"#588EEB",
			"#80AAEE",
			"#6B9CED",
			"#94B9F1",
			"#AAC8F2",
			"#C1D7F5",
			"#D9E6F6",
			"#F1F5F9",
		],
		summary: "시도/시군구 단위의 상위 10개 유입지역 제공",
		isSingleTable: true,
		chartUnit: "명",
		isExceptionalChart: true,
	},
	{
		name: "llpStayDaysInboundRegionRatioData",
		title: "체류일수별 유입지역 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF"],
		summary: "체류일수 범주별 시도 단위 상위 5개 유입지역 제공",
		chartUnit: "%",
	},
	{
		name: "llpAverageStayDaysPerRegionData",
		title: "유입지역별 평균 체류일수",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF"],
		summary: "시도 단위의 상위 5개 유입지역 제공",
		chartUnit: "일",
	},
	{
		name: "llpStayTimeCompareData",
		title: "체류시간별 인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		summary:
			"3시간 이상 체류인구를 기준으로 1시간 이상 체류인구와 2시간 이상 체류인구와의 비교",
		chartUnit: "명(누적)",
	},
	{
		name: "llpAvgStayTimeData",
		title: "평균 체류시간",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		summary: "체류인구가 한 달 동안 체류지역에 체류한 시간의 합을 체류한 일수의 합으로 나눈 값",
		chartUnit: "시간",
	},
	{
		name: "llpDailyStayTimeTrendData",
		title: "일별 체류시간별 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "llpStayTimeGenderRatioData",
		title: "체류시간별 성별 분포",
		type: ["bar", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "%",
		isExceptionalChart: true,
	},
	{
		name: "llpStayTimeAgeGroupRatioData",
		title: "체류시간별 연령별 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		isSingleTable: true,
		chartUnit: "명",
		// chartUnit: "%",
		isExceptionalChart: true,
	},

	//랭킹분석
	{
		name: "llpPreYearData",
		title: "주요 지표별 증감 추이",
		type: ["radar", "table"],
		xlabel: "구분",
		color: ["rgba(124, 105, 239, 0.6)", "rgba(47, 128, 237, 1)"],
		chartUnit: "%",
		isSingleTable: true,
	},
	{
		name: "llpFlowData",
		title: "체류인구 유입 분포",
		type: ["sankey", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#7C69EF", "#5789AF", "#16BFD6", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "llpRaceData",
		title: "시군구 지역 랭킹",
		type: ["tableGroup", "race", "bump"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},

	// 비교화면 체류인구현황
	{
		name: "llpMapDataGroup",
		title: "전국 인구감소지역 체류인구 배수",
		type: ["map"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "배",
	},
	{
		name: "llpPreYMonthDataGroup",
		title: "전년 동기 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "llpPremonthDataGroup",
		title: "전월 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "llpHourDayDataGroup",
		title: "일별 체류인구 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "llpHourWeekDataGroup",
		title: "평일/휴일별 체류인구",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "llpHourWeekPerDataGroup",
		title: "평일/휴일별 체류인구 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "%",
	},
	// {
	// 	name: "llpDistrictDataGroup",
	// 	title: "하위 행정구역별 체류인구 비중",
	// 	type: ["bar", "horizontalBar", "table"],
	// 	xlabel: "구분",
	// 	color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF"],
	// },
	{
		name: "llpGenderAgeDataGroup",
		title: "성연령별 체류인구 분포",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#5372F6", "#FF6362"],
		isSingleTable: true,
		chartUnit: "명",
		isExceptionalChart: true,
	},
	{
		name: "llpMonthGenderDataGroup",
		title: "월별 연령대별 체류인구 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
			"#FF7658",
			"#FF6BA1",
			"#94AE55",
			"#349D74",
			"#3A66B8",
			"#B94CAA",
		],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "llpCurrentDataGroup",
		title: "주민등록인구 대비 체류인구 현황",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#C4C4C4", "#79C8C4"],
		chartUnit: "명",
		isExceptionalChart: true,
	},
	{
		name: "llpMotchComparativeDataGroup",
		title: "월별 비교",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "llpHourMonthSexDataGroup",
		title: "성별 비교",
		type: ["custom", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "%",
	},
	{
		name: "llpHourMonthAgeDataGroup",
		title: "연령별 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "%",
	},

	//비교화면 체류인구특성
	{
		name: "llpStayDaysRatioDataGroup",
		title: "체류일수별 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		chartUnit: "명",
	},
	{
		name: "llpAvgDaysOfStayDataGroup",
		title: "평균 체류일수",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#79C8C4"],
		chartUnit: "일",
	},
	// {
	// 	name: "llpStayDaysPeopleDataGroup",
	// 	title: "체류일수별 체류인구",
	// 	type: ["bar", "table"],
	// 	xlabel: "구분",
	// 	color: ["#418AEC", "#79C8C4", "#7C69EF"],
	// },
	{
		name: "llpGenderStayDataGroup",
		title: "체류일수별 성별 분포",
		type: ["custom", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: "llpAgeGroupStayDataGroup",
		title: "체류일수별 연령별 분포",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
			"#FF7658",
			"#FF6BA1",
			"#94AE55",
			"#349D74",
			"#3A66B8",
			"#B94CAA",
		],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "llpStayOverRatioDataGroup",
		title: "숙박일수별 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "%",
	},
	{
		name: "llpAverageStayOverDaysDataGroup",
		title: "평균 숙박일수",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		chartUnit: "일",
	},
	// {
	// 	name: "llpShortStayRatioDataGroup",
	// 	title: "숙박일수별 비율",
	// 	type: ["fullStack", "table"],
	// 	xlabel: "구분",
	// 	color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
	// },

	{
		name: "llpGenderStayOverDataGroup",
		title: "숙박일수별 성별 분포",
		type: ["custom", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: "llpAgeGroupStayOverDataGroup",
		title: "숙박일수별 연령별 분포",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
			"#FF7658",
			"#FF6BA1",
			"#94AE55",
			"#349D74",
			"#3A66B8",
			"#B94CAA",
		],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "llpExternalResidentStayRatioDataGroup",
		title: "타시도 거주자 체류 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "%",
	},
	{
		name: "llpTop10InboundAreasDataGroup",
		title: "외부 유입지역 상위 TOP 10",
		type: ["horizontalBar", "bar", "table"],
		xlabel: "구분",
		color: [
			"#3473E7",
			"#4580E9",
			"#588EEB",
			"#80AAEE",
			"#6B9CED",
			"#94B9F1",
			"#AAC8F2",
			"#C1D7F5",
			"#D9E6F6",
			"#F1F5F9",
		],
		summary: "시도/시군구 단위의 상위 10개 유입지역 제공",
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "llpStayDaysInboundRegionRatioDataGroup",
		title: "체류일수별 유입지역 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF"],
		summary: "체류일수 범주별 시도 단위 상위 5개 유입지역 제공",
		chartUnit: "%",
		isSingleTable: true,
	},
	{
		name: "llpAverageStayDaysPerRegionDataGroup",
		title: "유입지역별 평균 체류일수",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF"],
		summary: "시도 단위의 상위 5개 유입지역 제공",
		chartUnit: "일",
	},
	{
		name: "llpStayTimeCompareDataGroup",
		title: "체류시간별 인구 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		summary:
			"3시간 이상 체류인구를 기준으로 하여 1시간 이상 체류인구와 2시간 이상 체류인구와의 비교",
		chartUnit: "명(누적)",
	},
	{
		name: "llpAvgStayTimeDataGroup",
		title: "평균 체류시간",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#79C8C4"],
		summary: "체류인구가 한 달 동안 체류지역에 체류한 시간의 합을 체류한 일수의 합으로 나눈 값",
		chartUnit: "시간",
	},
	{
		name: "llpDailyStayTimeTrendDataGroup",
		title: "일별 체류시간별 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "llpStayTimeGenderRatioDataGroup",
		title: "체류시간별 성별 분포",
		type: ["custom", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		chartUnit: "%",
		isExceptionalChart: true,
	},
	{
		name: "llpStayTimeAgeGroupRatioDataGroup",
		title: "체류시간별 연령별 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF"],
		isSingleTable: true,
		chartUnit: "%",
		isExceptionalChart: true,
	},

	//비교화면 랭킹분석
	{
		name: "llpPreYearDataGroup",
		title: "주요 지표별 증감 추이",
		type: ["radar", "table"],
		xlabel: "구분",
		color: ["rgba(124, 105, 239, 0.1)", "rgba(60, 143, 237, 0.35)"],
		chartUnit: "%",
		isSingleTable: true,
	},
	{
		name: "llpFlowDataGroup",
		title: "체류인구 유입 분포",
		type: ["sankey", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#7C69EF", "#5789AF", "#16BFD6", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "llpRaceDataGroup",
		title: "시군구 지역 랭킹",
		type: ["tableGroup", "race", "bump"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
];
