/* 
* ALP version 1.0

* Copyright © 2024 kt corp. All rights reserved.

* 

* This is a proprietary software of kt corp, and you may not use this file except in

* compliance with license agreement with kt corp. Any redistribution or use of this

* software, with or without modification shall be strictly prohibited without prior written

* approval of kt corp, and the copyright notice above does not evidence any actual or

* intended publication of such software.

*/

interface ChartConfig {
	name: string | string[];
	title: string;
	type: string | string[];
	xlabel: string;
	color: string[];
	summary?: string;
	isSingleTable?: boolean;
	isExceptionalChart?: boolean;
	chartUnit: string;
}

export const mopChartConfig: ChartConfig[] = [
	//생활이동현황 지역 비교분석
	{
		name: "mopFlowData",
		title: "생활이동 유입유출 분포",
		type: ["sankey", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF"],
		chartUnit: "명",
	},
	{
		name: "mopLastyearData",
		title: "전년 동기 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopPreMonthData",
		title: "전월 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopDailyMoveTrendData",
		title: "일별 이동 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopWeekPopData",
		title: "요일별 이동 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopWeekdayHolidayMoveData",
		title: "평일,휴일별 이동 분포",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "%",
	},
	{
		name: "mopArrivalTimePopData",
		title: "도착시간대별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "mopDepartOutData",
		title: "출발시간대별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "mopTimeMoveTrendDataData",
		title: "시간대별 이동 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "mopGenderData",
		title: "성별 이동 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopAgeData",
		title: "연령별 이동 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopGenderAgeInflowData",
		title: "성연령별 유입인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopGenderAgeOutflowData",
		title: "성연령별 유출인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopPurposeData",
		title: "이동목적별 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopTransData",
		title: "이동수단별 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	//생활이동현황 지역 출도착지 분석  ODD Origin-Destination
	{
		name: "oddFlowData",
		title: "생활이동 유입유출 분포",
		type: ["sankey", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#7C69EF", "#5789AF", "#16BFD6", "#79C8C4"],
		chartUnit: "명",
		isExceptionalChart: true,
	},
	{
		name: "oddLastyearData",
		title: "전년 동기 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "oddPreMonthData",
		title: "전월 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "oddDailyMoveTrendData",
		title: "일별 이동 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddWeekPopData",
		title: "요일별 이동 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "oddWeekdayHolidayMoveData",
		title: "평일,휴일별 이동 분포",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "oddArrivalTimePopData",
		title: "도착시간대별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "oddDepartOutData",
		title: "출발시간대별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "oddGenderData",
		title: "성별 이동 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: "oddAgeData",
		title: "연령별 이동 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
			"#FF7658",
			"#FF6BA1",
			"#94AE55",
			"#349D74",
			"#3A66B8",
			"#B94CAA",
		],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddGenderAgeInflowData",
		title: "성연령별 유입인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddGenderAgeOutflowData",
		title: "성연령별 유출인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurposeData",
		title: "이동목적별 분포",
		type: ["bar", "pie", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "oddTransData",
		title: "이동수단별 분포",
		type: ["bar", "pie", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	//이동목적분석 - 기준지역 출발 도착에 따라 다름
	{
		name: "purposeMoveInflowData",
		title: "이동목적별 유입 규모",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "purposeMoveOutflowData",
		title: "이동목적별 유출 규모",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "purposeMoveInflowRatioData",
		title: "이동목적별 유입 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "purposeMoveOutflowRatioData",
		title: "이동목적별 유출 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "purposeRegionMoveOutflowData",
		title: "도착지역별 이동목적별 유출 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "purposeRegionMoveInflowData",
		title: "출발지역별 이동목적별 유입 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "purposeRegionMoveOutflowRatioData",
		title: "도착지역별 이동목적별 유출 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "%",
		isSingleTable: true,
	},
	{
		name: "purposeRegionMoveInflowRatioData",
		title: "출발지역별 이동목적별 유입 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "%",
		isSingleTable: true,
	},

	{
		name: "purposeDayMoveInflowTrendData",
		title: "일별 이동목적별 유입 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "purposeDayMoveOutflowTrendData",
		title: "일별 이동목적별 유출 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "purposeWeekMoveInflowData",
		title: "요일별 이동목적별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "purposeWeekMoveOutflowData",
		title: "요일별 이동목적별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "purposeWeekdayHolidayMoveInflowData",
		title: "평일/휴일별 이동목적별 유입인구",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "purposeWeekdayHolidayMoveOutflowData",
		title: "평일/휴일별 이동목적별 유출인구",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "purposeDepartTimeMoveOutflowData",
		title: "출발시간대별 이동목적별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "purposeArriveTimeMoveInflowData",
		title: "도착시간대별 이동목적별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "purposeGenMoveInflowData",
		title: "성별 이동목적별 유입인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "purposeGenMoveOutflowData",
		title: "성별 이동목적별 유출인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},

	{
		name: "purposeAgeMoveInflowData",
		title: "연령별 이동목적별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "purposeAgeMoveOutflowData",
		title: "연령별 이동목적별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		isSingleTable: true,
		chartUnit: "명",
	},

	//이동목적분석 - 출도착지 분석  ODD Origin-Destination
	{
		name: "oddPurMoveInflowData",
		title: "이동목적별 유입 규모",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "oddPurMoveOutflowData",
		title: "이동목적별 유출 규모",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "oddPurMoveInflowRatioData",
		title: "이동목적별 유입 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "oddPurMoveOutflowRatioData",
		title: "이동목적별 유출 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "oddPurRegionMoveOutflowData",
		title: "도착지역별 이동목적별 유출 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurRegionMoveInflowData",
		title: "출발지역별 이동목적별 유입 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddPurRegionMoveOutflowRatioData",
		title: "도착지역별 이동목적별 유출 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "%",
		isSingleTable: true,
	},
	{
		name: "oddPurRegionMoveInflowRatioData",
		title: "출발지역별 이동목적별 유입 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "%",
		isSingleTable: true,
	},

	{
		name: "oddPurDayMoveInflowTrendData",
		title: "일별 이동목적별 유입 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurDayMoveOutflowTrendData",
		title: "일별 이동목적별 유출 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddPurWeekMoveInflowData",
		title: "요일별 이동목적별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurWeekMoveOutflowData",
		title: "요일별 이동목적별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddPurWeekdayHolidayMoveInflowData",
		title: "평일/휴일별 이동목적별 유입인구",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "oddPurWeekdayHolidayMoveOutflowData",
		title: "평일/휴일별 이동목적별 유출인구",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "oddPurDepartTimeMoveOutflowData",
		title: "출발시간대별 이동목적별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurArriveTimeMoveInflowData",
		title: "도착시간대별 이동목적별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddPurGenMoveInflowData",
		title: "성별 이동목적별 유입인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurGenMoveOutflowData",
		title: "성별 이동목적별 유출인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddPurAgeMoveInflowData",
		title: "연령별 이동목적별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurAgeMoveOutflowData",
		title: "연령별 이동목적별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	//이동수단분석 - 기준지역 출발 도착에 따라 다름
	{
		name: "transMoveInflowData",
		title: "이동수단별 유입 규모",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},
	{
		name: "transMoveOutflowData",
		title: "이동수단별 유출 규모",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	{
		name: "transMoveInflowRatioData",
		title: "이동수단별 유입 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},
	{
		name: "transMoveOutflowRatioData",
		title: "이동수단별 유출 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	{
		name: "transRegionMoveOutflowData",
		title: "도착지역별 이동수단별 유출 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "transRegionMoveInflowData",
		title: "출발지역별 이동수단별 유입 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "transRegionMoveOutflowRatioData",
		title: "도착지역별 이동수단 유출 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "%",
		isSingleTable: true,
	},
	{
		name: "transRegionMoveInflowRatioData",
		title: "출발지역별 이동수단 유입 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "%",
		isSingleTable: true,
	},

	{
		name: "transDayMoveInflowTrendData",
		title: "일별 이동수단별 유입 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "transDayMoveOutflowTrendData",
		title: "일별 이동수단별 유출 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "transWeekMoveInflowData",
		title: "요일별 이동수단별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "transWeekMoveOutflowData",
		title: "요일별 이동수단별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "transWeekdayHolidayMoveInflowData",
		title: "평일/휴일별 이동수단별 유입인구",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},
	{
		name: "transWeekdayHolidayMoveOutflowData",
		title: "평일/휴일별 이동수단별 유출인구",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	{
		name: "transArriveTimeMoveInflowData",
		title: "도착시간대별 이동수단별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "transDepartTimeMoveOutflowData",
		title: "출발시간대별 이동수단별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "transGenMoveInflowData",
		title: "성별 이동수단별 유입인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "transGenMoveOutflowData",
		title: "성별 이동수단별 유출인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},

	{
		name: "transAgeMoveInflowData",
		title: "연령별 이동수단별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "transAgeMoveOutflowData",
		title: "연령별 이동수단별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		isSingleTable: true,
		chartUnit: "명",
	},

	//이동수단분석 - 출도착지 분석  ODD Origin-Destination
	{
		name: "oddTraMoveInflowData",
		title: "이동수단별 유입 규모",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},
	{
		name: "oddTraMoveOutflowData",
		title: "이동수단별 유출 규모",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	{
		name: "oddTraMoveInflowRatioData",
		title: "이동수단별 유입 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},
	{
		name: "oddTraMoveOutflowRatioData",
		title: "이동수단별 유출 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	{
		name: "oddTraRegionMoveOutflowData",
		title: "도착지역별 이동수단별 유출 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddTraRegionMoveInflowData",
		title: "출발지역별 이동수단별 유입 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddTraRegionMoveOutflowRatioData",
		title: "도착지역별 이동수단 유출 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "%",
		isSingleTable: true,
	},
	{
		name: "oddTraRegionMoveInflowRatioData",
		title: "출발지역별 이동수단 유입 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "%",
		isSingleTable: true,
	},

	{
		name: "oddTraDayMoveInflowTrendData",
		title: "일별 이동수단별 유입 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddTraDayMoveOutflowTrendData",
		title: "일별 이동수단별 유출 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddTraWeekMoveInflowData",
		title: "요일별 이동수단별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddTraWeekMoveOutflowData",
		title: "요일별 이동수단별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddTraWeekdayHolidayMoveInflowData",
		title: "평일/휴일별 이동수단별 유입인구",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},
	{
		name: "oddTraWeekdayHolidayMoveOutflowData",
		title: "평일/휴일별 이동수단별 유출인구",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	{
		name: "oddTraArriveTimeMoveInflowData",
		title: "도착시간대별 이동수단별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddTraDepartTimeMoveOutflowData",
		title: "출발시간대별 이동수단별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddTraGenMoveInflowData",
		title: "성별 이동수단별 유입인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "oddTraGenMoveOutflowData",
		title: "성별 이동수단별 유출인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},

	{
		name: "oddTraAgeMoveInflowData",
		title: "연령별 이동수단별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddTraAgeMoveOutflowData",
		title: "연령별 이동수단별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	//랭킹분석
	{
		name: "scatterData",
		title: "전국 시도별 인구 유입 및 유출 변화 분석",
		type: ["scatter", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#F9C74F"],
		chartUnit: "%",
	},
	{
		name: "mopRaceData",
		title: "시군구 지역 랭킹",
		type: ["tableGroup", "race", "bump"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopRaceTownData",
		title: "읍면동 지역 랭킹",
		type: ["tableGroup", "race", "bump"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},

	// 비교화면 생활이동현황
	{
		name: "mopFlowDataGroup",
		title: "생활이동 유입유출 분포",
		type: ["sankey", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#7C69EF", "#5789AF", "#16BFD6", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopLastyearDataGroup",
		title: "전년 동기 비교",
		type: ["custom", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopPreMonthDataGroup",
		title: "전월 비교",
		type: ["custom", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopDailyMoveTrendDataGroup",
		title: "일별 이동 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopWeekPopDataGroup",
		title: "요일별 이동 분포",
		type: ["bar", "tableGroup"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopWeekdayHolidayMoveDataGroup",
		title: "평일,휴일별 이동 분포",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopArrivalTimePopDataGroup",
		title: "도착시간대별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopDepartOutDataGroup",
		title: "출발시간대별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopTimeMoveTrendDataDataGroup",
		title: "시간대별 이동 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopGenderDataGroup",
		title: "성별 이동 분포",
		type: ["custom", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopAgeDataGroup",
		title: "연령별 이동 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopGenderAgeInflowDataGroup",
		title: "성연령별 유입인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopGenderAgeOutflowDataGroup",
		title: "성연령별 유출인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopPurposeDataGroup",
		title: "이동목적별 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "mopTransDataGroup",
		title: "이동수단별 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	//비교화면 생활이동현황 지역 출도착지 분석 ODD Origin-Destination
	{
		name: "oddFlowDataGroup",
		title: "생활이동 유입유출 분포",
		type: ["sankey", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#7C69EF", "#5789AF", "#16BFD6", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "oddLastyearDataGroup",
		title: "전년 동기 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "oddPreMonthDataGroup",
		title: "전월 비교",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#D8D8D8", "#418AEC"],
		chartUnit: "명",
	},
	{
		name: "oddDailyMoveTrendDataGroup",
		title: "일별 이동 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#7C69EF", "#5789AF", "#16BFD6"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddWeekPopDataGroup",
		title: "요일별 이동 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddWeekdayHolidayMoveDataGroup",
		title: "평일,휴일별 이동 분포",
		type: ["pie", "tableGroup"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "oddArrivalTimePopDataGroup",
		title: "도착시간대별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddDepartOutDataGroup",
		title: "출발시간대별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddGenderDataGroup",
		title: "성별 이동 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6362"],
		chartUnit: "명",
	},
	{
		name: "oddAgeDataGroup",
		title: "연령별 이동 분포",
		type: ["bar", "table"],
		xlabel: "구분",
		color: [
			"#418AEC",
			"#79C8C4",
			"#7C69EF",
			"#5BC7EE",
			"#5789AF",
			"#F9C74F",
			"#D63457",
			"#D4D4D4",
			"#999999",
			"#967367",
			"#FF7658",
			"#FF6BA1",
			"#94AE55",
			"#349D74",
			"#3A66B8",
			"#B94CAA",
		],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "oddGenderAgeInflowDataGroup",
		title: "성연령별 유입인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "oddGenderAgeOutflowDataGroup",
		title: "성연령별 유출인구",
		type: ["stack", "butterfly", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurposeDataGroup",
		title: "이동목적별 분포",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddTransDataGroup",
		title: "이동수단별 분포",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	//비교화면 이동목적분석 - 기준지역 출발 도착에 따라 다름
	{
		name: "purposeMoveInflowDataGroup",
		title: "이동목적별 유입 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "purposeMoveOutflowDataGroup",
		title: "이동목적별 유출 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "purposeMoveInflowRatioDataGroup",
		title: "이동목적별 유입 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "purposeMoveOutflowRatioDataGroup",
		title: "이동목적별 유출 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "purposeRegionMoveOutflowDataGroup",
		title: "도착지역별 이동목적별 유출 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "purposeRegionMoveInflowDataGroup",
		title: "출발지역별 이동목적별 유입 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "purposeRegionMoveOutflowRatioDataGroup",
		title: "도착지역별 이동목적별 유출 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "%",
		isSingleTable: true,
	},
	{
		name: "purposeRegionMoveInflowRatioDataGroup",
		title: "출발지역별 이동목적별 유입 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "%",
		isSingleTable: true,
	},

	{
		name: "purposeDayMoveInflowTrendDataGroup",
		title: "일별 이동목적별 유입 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "purposeDayMoveOutflowTrendDataGroup",
		title: "일별 이동목적별 유출 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "purposeWeekMoveInflowDataGroup",
		title: "요일별 이동목적별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "purposeWeekMoveOutflowDataGroup",
		title: "요일별 이동목적별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "purposeWeekdayHolidayMoveInflowDataGroup",
		title: "평일/휴일별 이동목적별 유입인구",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "purposeWeekdayHolidayMoveOutflowDataGroup",
		title: "평일/휴일별 이동목적별 유출인구",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "purposeDepartTimeMoveOutflowDataGroup",
		title: "출발시간대별 이동목적별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "purposeArriveTimeMoveInflowDataGroup",
		title: "도착시간대별 이동목적별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "purposeGenMoveInflowDataGroup",
		title: "성별 이동목적별 유입인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "purposeGenMoveOutflowDataGroup",
		title: "성별 이동목적별 유출인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},

	{
		name: "purposeAgeMoveInflowDataGroup",
		title: "연령별 이동목적별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "purposeAgeMoveOutflowDataGroup",
		title: "연령별 이동목적별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	//비교화면 이동목적분석 - 출도착지 분석  ODD Origin-Destination
	{
		name: "oddPurMoveInflowDataGroup",
		title: "이동목적별 유입 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "oddPurMoveOutflowDataGroup",
		title: "이동목적별 유출 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "oddPurMoveInflowRatioDataGroup",
		title: "이동목적별 유입 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurMoveOutflowRatioDataGroup",
		title: "이동목적별 유출 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddPurDayMoveInflowTrendDataGroup",
		title: "일별 이동목적별 유입 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurDayMoveOutflowTrendDataGroup",
		title: "일별 이동목적별 유출 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddPurWeekMoveInflowDataGroup",
		title: "요일별 이동목적별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurWeekMoveOutflowDataGroup",
		title: "요일별 이동목적별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddPurWeekdayHolidayMoveInflowDataGroup",
		title: "평일/휴일별 이동목적별 유입인구",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},
	{
		name: "oddPurWeekdayHolidayMoveOutflowDataGroup",
		title: "평일/휴일별 이동목적별 유출인구",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
	},

	{
		name: "oddPurDepartTimeMoveOutflowDataGroup",
		title: "출발시간대별 이동목적별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurArriveTimeMoveInflowDataGroup",
		title: "도착시간대별 이동목적별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddPurGenMoveInflowDataGroup",
		title: "성별 이동목적별 유입인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "oddPurGenMoveOutflowDataGroup",
		title: "성별 이동목적별 유출인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},

	{
		name: "oddPurAgeMoveInflowDataGroup",
		title: "연령별 이동목적별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddPurAgeMoveOutflowDataGroup",
		title: "연령별 이동목적별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457"],
		chartUnit: "명",
		isSingleTable: true,
	},

	//비교화면 이동수단분석 - 기준지역 출발 도착에 따라 다름
	{
		name: "transMoveInflowDataGroup",
		title: "이동수단별 유입 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},
	{
		name: "transMoveOutflowDataGroup",
		title: "이동수단별 유출 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	{
		name: "transMoveInflowRatioDataGroup",
		title: "이동수단별 유입 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "transMoveOutflowRatioDataGroup",
		title: "이동수단별 유출 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "transRegionMoveOutflowDataGroup",
		title: "도착지역별 이동수단별 유출 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "transRegionMoveInflowDataGroup",
		title: "출발지역별 이동수단별 유입 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "transRegionMoveOutflowRatioDataGroup",
		title: "도착지역별 이동수단 유출 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "%",
		isSingleTable: true,
	},
	{
		name: "transRegionMoveInflowRatioDataGroup",
		title: "출발지역별 이동수단 유입 비중",
		type: ["fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "%",
		isSingleTable: true,
	},

	{
		name: "transDayMoveInflowTrendDataGroup",
		title: "일별 이동수단별 유입 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "transDayMoveOutflowTrendDataGroup",
		title: "일별 이동수단별 유출 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "transWeekMoveInflowDataGroup",
		title: "요일별 이동수단별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "transWeekMoveOutflowDataGroup",
		title: "요일별 이동수단별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "transWeekdayHolidayMoveInflowDataGroup",
		title: "평일/휴일별 이동수단별 유입인구",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},
	{
		name: "transWeekdayHolidayMoveOutflowDataGroup",
		title: "평일/휴일별 이동수단별 유출인구",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	{
		name: "transArriveTimeMoveInflowDataGroup",
		title: "도착시간대별 이동수단별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "transDepartTimeMoveOutflowDataGroup",
		title: "출발시간대별 이동수단별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		isSingleTable: true,
		chartUnit: "명",
	},

	{
		name: "transGenMoveInflowDataGroup",
		title: "성별 이동수단별 유입인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "transGenMoveOutflowDataGroup",
		title: "성별 이동수단별 유출인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},

	{
		name: "transAgeMoveInflowDataGroup",
		title: "연령별 이동수단별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "transAgeMoveOutflowDataGroup",
		title: "연령별 이동수단별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		isSingleTable: true,
		chartUnit: "명",
	},

	//비교화면 이동수단분석 - 출도착지 분석  ODD Origin-Destination
	{
		name: "oddTraMoveInflowDataGroup",
		title: "이동수단별 유입 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},
	{
		name: "oddTraMoveOutflowDataGroup",
		title: "이동수단별 유출 규모",
		type: ["stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	{
		name: "oddTraMoveInflowRatioDataGroup",
		title: "이동수단별 유입 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddTraMoveOutflowRatioDataGroup",
		title: "이동수단별 유출 비중",
		type: ["pie", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddTraDayMoveInflowTrendDataGroup",
		title: "일별 이동수단별 유입 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddTraDayMoveOutflowTrendDataGroup",
		title: "일별 이동수단별 유출 추이",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddTraWeekMoveInflowDataGroup",
		title: "요일별 이동수단별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddTraWeekMoveOutflowDataGroup",
		title: "요일별 이동수단별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddTraWeekdayHolidayMoveInflowDataGroup",
		title: "평일/휴일별 이동수단별 유입인구",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},
	{
		name: "oddTraWeekdayHolidayMoveOutflowDataGroup",
		title: "평일/휴일별 이동수단별 유출인구",
		type: ["customStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
	},

	{
		name: "oddTraArriveTimeMoveInflowDataGroup",
		title: "도착시간대별 이동수단별 유입인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},
	{
		name: "oddTraDepartTimeMoveOutflowDataGroup",
		title: "출발시간대별 이동수단별 유출인구",
		type: ["line", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		chartUnit: "명",
		isSingleTable: true,
	},

	{
		name: "oddTraGenMoveInflowDataGroup",
		title: "성별 이동수단별 유입인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "oddTraGenMoveOutflowDataGroup",
		title: "성별 이동수단별 유출인구",
		type: ["bar", "stack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#FF6262"],
		isSingleTable: true,
		chartUnit: "명",
	},

	{
		name: "oddTraAgeMoveInflowDataGroup",
		title: "연령별 이동수단별 유입인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		isSingleTable: true,
		chartUnit: "명",
	},
	{
		name: "oddTraAgeMoveOutflowDataGroup",
		title: "연령별 이동수단별 유출인구",
		type: ["stack", "fullStack", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#5789AF", "#F9C74F", "#D63457", "#D4D4D4"],
		isSingleTable: true,
		chartUnit: "명",
	},

	//비교화면 랭킹분석
	{
		name: "scatterDataGroup",
		title: "전국 시도별 인구 유입 및 유출 변화 분석",
		type: ["scatter", "table"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4", "#7C69EF", "#5BC7EE", "#F9C74F"],
		chartUnit: "%",
	},
	{
		name: "mopRaceDataGroup",
		title: "시군구 지역 랭킹",
		type: ["tableGroup", "race", "bump"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
	{
		name: "mopRaceTownDataGroup",
		title: "읍면동 지역 랭킹",
		type: ["tableGroup", "race", "bump"],
		xlabel: "구분",
		color: ["#418AEC", "#79C8C4"],
		chartUnit: "명",
	},
];
