# ALP version 1.0
# Copyright © 2024 kt corp. All rights reserved.
#
# This is a proprietary software of kt corp, and you may not use this file except in
# compliance with a license agreement with kt corp. Any redistribution or use of this
# software, with or without modification, shall be strictly prohibited without prior written
# approval of kt corp. The copyright notice above does not evidence any actual or
# intended publication of such software.

components:
  schemas:
    Datainfo:
      type: object
      properties:
        START:
          type: string
          example: "20230101"
          description: Data storage starting date (YYYYMMDD format)
        END:
          type: string
          example: "20241231"
          description: Data storage ending date (YYYYMMDD format)
        DATE:
          type: string
          example: "20240101"
          description: checking date (YYYYMMDD format)
        DESC:
          type: string
          example: "Data Successfully Loaded on 20241231"
          description: Checking the data index
